name: saloon_dashboard
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^1.1.2
  font_awesome_flutter: ^8.10.0
  flutter_swiper: ^1.1.6
  syncfusion_flutter_calendar: ^18.3.42
  animations: ^1.1.2
  route_transitions: ^1.0.2
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  provider: ^4.3.2+2
  cached_network_image: ^2.3.3
  cloud_firestore: ^0.14.2
  curved_navigation_bar: ^0.3.4
  google_sign_in: 4.5.6
  flutter_rating_bar: ^3.2.0
  intl: ^0.16.1
  paginate_firestore: ^0.2.2
  firebase_messaging: ^7.0.3
  image_picker: ^0.6.7+14
  firebase_storage: ^5.1.0
  path_provider: ^1.6.24
  multiselect_formfield: ^0.1.5


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/saloon_gallery/
    - assets/images/categories/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat Alternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
